### ISSUE TITLE
cannot create pod 

### ISSUE THREAD

**Issue by fullbird** [ApsaraDB/galaxykube#1]
$ kubectl get polardbxcluster -w
NAME   GMS   CN    DN    CDC   PHASE      DISK   AGE
liyz   0/1   0/1   0/1   0/1   Creating          42m
alway waiting.
$ kubectl get pods
NAME                      READY   STATUS    RESTARTS   AGE
liyz-9gk8-dn-0-single-0   2/3     Running   0          43m
liyz-9gk8-gms-single-0    2/3     Running   0          43m
$ kubectl logs --tail=30 liyz-9gk8-dn-0-single-0 --all-containers=true
INFO:root:Begin to initialize...
2022-04-07 08:31:23,861 - GalaxyEngine - INFO - (cwd=/data/mysql/data) execute command: /opt/galaxy_engine/bin/mysqld --defaults-file=/data/mysql/conf/my.cnf --loose-pod-name=liyz-9gk8-dn-0-single-0 --loose-cluster-info=liyz-9gk8-dn-0-single-0:25047@1 --initialize-insecure
INFO:root:Initialized!
INFO:root:Bootstrapping engine galaxy ...
2022-04-07 08:31:27,665 - GalaxyEngine - INFO - starting process...
2022-04-07 08:31:27,665 - GalaxyEngine - INFO - () start command: /opt/galaxy_engine/bin/mysqld_safe --defaults-file=/data/mysql/conf/my.cnf --loose-pod-name=liyz-9gk8-dn-0-single-0
2022-04-07T08:31:28.433699Z mysqld_safe Logging to '/data/mysql/log/alert.log'.
2022-04-07T08:31:28.447407Z mysqld_safe Starting mysqld daemon with databases from /data/mysql/data
level=info ts=2022-04-07T08:32:02.795Z caller=mysqld_exporter.go:277 msg="Starting msqyld_exporter" version="(version=0.13.0, branch=master, revision=4e8e2b98de1c2bcfed7bf0a5c08b3a885b1cbf46)"
level=info ts=2022-04-07T08:32:02.795Z caller=mysqld_exporter.go:278 msg="Build context" (gogo1.16.9,userroot@eafbaf7294c5,date20211023-07:52:42)=(MISSING)
level=info ts=2022-04-07T08:32:02.795Z caller=mysqld_exporter.go:293 msg="Scraper enabled" scraper=global_status
level=info ts=2022-04-07T08:32:02.795Z caller=mysqld_exporter.go:293 msg="Scraper enabled" scraper=global_variables
level=info ts=2022-04-07T08:32:02.795Z caller=mysqld_exporter.go:293 msg="Scraper enabled" scraper=slave_status
level=info ts=2022-04-07T08:32:02.795Z caller=mysqld_exporter.go:293 msg="Scraper enabled" scraper=info_schema.processlist
level=info ts=2022-04-07T08:32:02.795Z caller=mysqld_exporter.go:293 msg="Scraper enabled" scraper=info_schema.innodb_tablespaces
level=info ts=2022-04-07T08:32:02.795Z caller=mysqld_exporter.go:293 msg="Scraper enabled" scraper=info_schema.innodb_metrics
level=info ts=2022-04-07T08:32:02.795Z caller=mysqld_exporter.go:293 msg="Scraper enabled" scraper=info_schema.innodb_cmp
level=info ts=2022-04-07T08:32:02.795Z caller=mysqld_exporter.go:293 msg="Scraper enabled" scraper=info_schema.innodb_cmpmem
level=info ts=2022-04-07T08:32:02.795Z caller=mysqld_exporter.go:293 msg="Scraper enabled" scraper=info_schema.query_response_time
level=info ts=2022-04-07T08:32:02.795Z caller=mysqld_exporter.go:293 msg="Scraper enabled" scraper=engine_innodb_status
level=info ts=2022-04-07T08:32:02.795Z caller=mysqld_exporter.go:303 msg="Listening on address" address=:21897
level=info ts=2022-04-07T08:32:02.795Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
Client: 192.168.49.2:47238
GET /liveness HTTP/1.1
Host: 192.168.49.2:22096
probe-port: 17047
probe-target: xstore
connection: close
user-agent: kube-probe/1.23
accept: */*
probe-extra: galaxy
Client: 192.168.49.2:47236
GET /readiness HTTP/1.1
Host: 192.168.49.2:22096
probe-extra: galaxy
probe-port: 17047
probe-target: xstore
connection: close
user-agent: kube-probe/1.23
accept: */*
2022/04/07 09:12:00 Succeeds!
2022/04/07 09:12:00 Failed!
Client: 192.168.49.2:47254
GET /readiness HTTP/1.1
Host: 192.168.49.2:22096
probe-target: xstore
connection: close
user-agent: kube-probe/1.23
accept: */*
probe-extra: galaxy
probe-port: 17047
2022/04/07 09:12:01 Failed!

**Comment by fullbird** [comment]
mirror错误，改成下面就ok:https://docker.mirrors.sjtug.sjtu.edu.cn

**Comment by arkbriar** [comment]
Thanks for reporting the mirror issue. 
We've revised the [doc](https://github.com/ApsaraDB/galaxykube/blob/main/docs/zh/deploy/quick-start.md). Thus I'm going to close the issue.
