### ISSUE TITLE
健康检查一直无法通过

### ISSUE THREAD

**Issue by sj-dev** [ApsaraDB/galaxykube#5]
Client: 10.1.8.242:57568
GET /liveness HTTP/1.1
Host: 10.1.8.242:23234
user-agent: kube-probe/1.21
accept: */*
probe-extra: galaxy
probe-port: 17997
probe-target: xstore
connection: close
2022/08/12 21:20:44 Succeeds!
2022/08/12 21:20:44 Failed!

**Comment by vettalwu** [comment]
It seems that the dn is not running. Please disable the dn healthy check using the following commnad:
```
kubectl annotate pod -l polardbx/role=dn runmode=debug
```
Then login the dn pod and check `/data/mysql/log/alert.log`
